Repository tomschroeter/webtechnologien, pull requests merged in 2025-04, with the labels that each got.

#29 feat: Home Page
  .env.template
  .gitignore
  README.md
  assets/style.css
  assets/svgs/logo.svg
  assets/svgs/profile.svg
  bootstrap.php
  components/most-reviewed-artists.php
  components/random-carousel.php
  components/recent-reviews.php
  components/top-rated.php
  db.php
  env.php
  head.php
  index.php
  navbar.php
  router/router.php
  router/routes.php
  test/index.php
Labels: documentation, enhancement

#42 Feat: Browse Subjects
  artists.php
  classes/Subject.php
  navbar.php
  repositories/SubjectRepository.php
  subjects.php
Labels: enhancement, design

#38 Feat: Display Single Artist
  .htaccess
  artists.php
  classes/Artwork.php
  display-single-artist.php
  error.php
  navbar.php
  repositories/ArtistRepository.php
  repositories/ArtworkRepository.php
  router/router.php
  router/routes.php
Labels: enhancement

#44 Feat: Missing Images
  artists.php
  assets/placeholder/artists/medium/placeholder.svg
  assets/placeholder/artists/square-medium/placeholder.svg
  assets/placeholder/artists/square-thumb/placeholder.svg
  assets/placeholder/genres/square-medium/placeholder.svg
  assets/placeholder/genres/square-thumbs/placeholder.svg
  assets/placeholder/subjects/square-medium/placeholder.svg
  assets/placeholder/subjects/square-thumbs/placeholder.svg
  assets/placeholder/works/large/placeholder.svg
  assets/placeholder/works/medium/placeholder.svg
  assets/placeholder/works/small/placeholder.svg
  assets/placeholder/works/square-medium/placeholder.svg
  assets/placeholder/works/square-small/plcaeholder.svg
  display-single-artist.php
  repositories/ArtistRepository.php
  subjects.php
Labels: design

#45 Feat: Simple Search + Search Results
  artists.php
  assets/placeholder/works/square-small/placeholder.svg
  display-single-artist.php
  dtos/ArtworkWithArtistName.php
  error.php
  navbar.php
  repositories/ArtistRepository.php
  repositories/ArtworkRepository.php
  search.php
Labels: enhancement
